const baseRates={types:[2,4,5],extras:[15,80,25,20]};
let rates=JSON.parse(localStorage.getItem("clearlyRates")||"null")||structuredClone(baseRates);
let state={lang:localStorage.getItem("clearlyLang")||"ru",currency:localStorage.getItem("clearlyCurrency")||"GEL",type:0,extras:[]};
const fx={GEL:1,USD:1/2.7},sym={GEL:"₾",USD:"$"};
const t={
ru:{tag:"УБОРКА. ПО ПОЛОЧКАМ.",title:"Калькулятор уборки",subtitle:"От площади до готового предложения — за пару минут.",calc:"Расчёт",history:"История",rates:"Тарифы",cleaning:"Какая уборка нужна?",area:"Площадь помещения",extras:"Добавим детали",client:"Для кого считаем?",terms:"Условия предложения",discount:"Скидка, %",valid:"Срок действия, дней",yourcalc:"ВАШ РАСЧЁТ",save:"Сохранить расчёт",proposal:"Предложение / PDF",disclaimer:"Предварительная стоимость. Финальные условия согласуются с клиентом.",footer:"Меньше расчётов. Больше ясности.",name:"Имя клиента",address:"Адрес уборки",note:"Примечание для клиента",historyHint:"Сохранённые расчёты хранятся на этом устройстве.",clear:"Очистить историю",ratesHint:"Настройте цены своей компании. Они сохранятся на этом устройстве.",saveRates:"Сохранить тарифы",resetRates:"Вернуть стандартные",types:[["Поддерживающая","Чистота на каждый день"],["Генеральная","Внимание к каждой детали"],["После ремонта","Готово к новому началу"]],extrasList:[["Мытьё окон","С двух сторон, за створку"],["Химчистка дивана","До 3 посадочных мест"],["Духовой шкаф","Внутри и снаружи"],["Холодильник","Внутри и снаружи"]]},
en:{tag:"CLEANING. MADE CLEAR.",title:"Cleaning calculator",subtitle:"From area to a ready quote in minutes.",calc:"Quote",history:"History",rates:"Rates",cleaning:"What cleaning do you need?",area:"Property area",extras:"Add details",client:"Who is the quote for?",terms:"Quote terms",discount:"Discount, %",valid:"Valid for, days",yourcalc:"YOUR QUOTE",save:"Save quote",proposal:"Quote / PDF",disclaimer:"Estimated price. Final terms are agreed with the client.",footer:"Less calculating. More clarity.",name:"Client name",address:"Cleaning address",note:"Note for client",historyHint:"Saved quotes are stored on this device.",clear:"Clear history",ratesHint:"Set your company's prices. They are stored on this device.",saveRates:"Save rates",resetRates:"Restore defaults",types:[["Maintenance","Everyday cleanliness"],["Deep cleaning","Attention to every detail"],["Post-renovation","Ready for a fresh start"]],extrasList:[["Window cleaning","Both sides, per sash"],["Sofa cleaning","Up to 3 seats"],["Oven","Inside and outside"],["Refrigerator","Inside and outside"]]},
ka:{tag:"დასუფთავება. მარტივად.",title:"დასუფთავების კალკულატორი",subtitle:"ფართობიდან მზა შეთავაზებამდე — რამდენიმე წუთში.",calc:"გაანგარიშება",history:"ისტორია",rates:"ტარიფები",cleaning:"რომელი დასუფთავება გჭირდებათ?",area:"ფართობი",extras:"დამატებითი მომსახურება",client:"ვისთვის ვითვლით?",terms:"შეთავაზების პირობები",discount:"ფასდაკლება, %",valid:"მოქმედების ვადა, დღე",yourcalc:"თქვენი გაანგარიშება",save:"შენახვა",proposal:"შეთავაზება / PDF",disclaimer:"სავარაუდო ღირებულება. საბოლოო პირობები შეთანხმდება კლიენტთან.",footer:"ნაკლები გამოთვლა. მეტი სიცხადე.",name:"კლიენტის სახელი",address:"დასუფთავების მისამართი",note:"შენიშვნა კლიენტისთვის",historyHint:"შენახული გაანგარიშებები ინახება ამ მოწყობილობაზე.",clear:"ისტორიის გასუფთავება",ratesHint:"დააყენეთ თქვენი კომპანიის ფასები. ისინი შეინახება ამ მოწყობილობაზე.",saveRates:"ტარიფების შენახვა",resetRates:"სტანდარტულის დაბრუნება",types:[["მხარდამჭერი","ყოველდღიური სისუფთავე"],["გენერალური","ყურადღება ყველა დეტალზე"],["რემონტის შემდეგ","მზად ახალი დასაწყისისთვის"]],extrasList:[["ფანჯრების წმენდა","ორივე მხრიდან"],["დივნის ქიმწმენდა","3 ადგილამდე"],["ღუმელი","შიგნიდან და გარედან"],["მაცივარი","შიგნიდან და გარედან"]]}
};
const $=x=>document.getElementById(x),D=()=>t[state.lang];
function money(g){return state.currency==="GEL"?`${Math.round(g)} ₾`:`$${(g*fx.USD).toFixed(2)}`}
function render(){document.documentElement.lang=state.lang;$("lang").value=state.lang;$("currency").value=state.currency;document.querySelectorAll("[data-t]").forEach(e=>e.textContent=D()[e.dataset.t]);document.querySelectorAll("[data-ph]").forEach(e=>e.placeholder=D()[e.dataset.ph]);$("types").innerHTML=D().types.map((x,i)=>`<div class="option ${i===state.type?"active":""}" data-type="${i}"><b>${x[0]}</b><small>${x[1]}</small><span>${money(rates.types[i])} / m²</span></div>`).join("");$("extras").innerHTML=D().extrasList.map((x,i)=>`<div class="option ${state.extras.includes(i)?"active":""}" data-extra="${i}"><b>${x[0]}</b><small>${x[1]}</small><span>+ ${money(rates.extras[i])}</span></div>`).join("");document.querySelectorAll("[data-type]").forEach(e=>e.onclick=()=>{state.type=+e.dataset.type;render()});document.querySelectorAll("[data-extra]").forEach(e=>e.onclick=()=>{let i=+e.dataset.extra;state.extras=state.extras.includes(i)?state.extras.filter(v=>v!==i):[...state.extras,i];render()});calc();history();rateEditor()}
function calc(){let a=+$("area").value,b=a*rates.types[state.type],ex=state.extras.reduce((s,i)=>s+rates.extras[i],0),sub=b+ex,di=Math.min(100,Math.max(0,+$("discount").value||0)),total=sub*(1-di/100);$("areaValue").textContent=a+" m²";$("total").textContent=money(total);$("breakdown").innerHTML=`<div class="line"><span>${D().types[state.type][0]} · ${a} m²</span><b>${money(b)}</b></div>`+state.extras.map(i=>`<div class="line"><span>${D().extrasList[i][0]}</span><b>${money(rates.extras[i])}</b></div>`).join("")+(di?`<div class="line"><span>-${di}%</span><b>-${money(sub-total)}</b></div>`:"");return total}
function history(){let h=JSON.parse(localStorage.getItem("clearlyHistory")||"[]");$("historyList").innerHTML=h.length?h.map(x=>`<div class="historyItem"><div><b>${x.name||"—"}</b><br><small>${x.date}</small></div><b>${x.total}</b></div>`).join(""):"—"}
function rateEditor(){$("rateEditor").innerHTML=D().types.map((x,i)=>`<div class="rateRow"><span>${x[0]} / m²</span><input type="number" min="0" step=".1" data-rt="${i}" value="${rates.types[i]}"></div>`).join("")+D().extrasList.map((x,i)=>`<div class="rateRow"><span>${x[0]}</span><input type="number" min="0" step=".1" data-re="${i}" value="${rates.extras[i]}"></div>`).join("")}
$("area").oninput=calc;$("discount").oninput=calc;
$("lang").onchange=e=>{state.lang=e.target.value;localStorage.setItem("clearlyLang",state.lang);render()};
$("currency").onchange=e=>{state.currency=e.target.value;localStorage.setItem("clearlyCurrency",state.currency);render()};
$("save").onclick=()=>{let h=JSON.parse(localStorage.getItem("clearlyHistory")||"[]");h.unshift({total:$("total").textContent,name:$("name").value,date:new Date().toLocaleString(),address:$("address").value});localStorage.setItem("clearlyHistory",JSON.stringify(h.slice(0,50)));history()};
$("print").onclick=()=>window.print();
$("clearHistory").onclick=()=>{localStorage.removeItem("clearlyHistory");history()};
$("saveRates").onclick=()=>{document.querySelectorAll("[data-rt]").forEach(e=>rates.types[+e.dataset.rt]=Math.max(0,+e.value||0));document.querySelectorAll("[data-re]").forEach(e=>rates.extras[+e.dataset.re]=Math.max(0,+e.value||0));localStorage.setItem("clearlyRates",JSON.stringify(rates));render()};
$("resetRates").onclick=()=>{rates=structuredClone(baseRates);localStorage.removeItem("clearlyRates");render()};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.page).classList.add("active")});
render();